### ISSUE TITLE
moosh uses homedir of user, even when sudo is used

### ISSUE THREAD

**Issue by usernamenumber** [tmuras/moosh#138]
It looks like it's best practice to run moosh as the owner of your Moodle install, e.g. `sudo -u www-data moosh ...`. 

However, the `home_dir()` function in `includes/functions.php` just grabs the value of `$HOME` which in an example like the above is still set to the original user's homedir. As a result, moosh ends up attempting to access `/home/$my_user/.moosh/` as `www-data`, which of course gets a permission error.

Am I missing something?

**Comment by usernamenumber** [comment]
Quick and dirty workaround:

`HOME=/var/www  sudo -u www-data moosh ...`

**Comment by tmuras** [comment]
Try sudo with -H option, from sudo help:
  -H, --set-home              set HOME variable to target user's home dir

**Comment by usernamenumber** [comment]
Sure, but if this means following best practices (running as e.g. www-data) will cause moosh to fail in at least any Debian/Ubuntu-derived environment unless you pass a special argument to sudo, wouldn't it be best to change the code so that, at least on *nix systems, the `how_dir()` function, say, looks up the correct directory in `/etc/passwd`?

If nothing else, maybe a note at the top of the commands page telling people to use sudo -H?

**Comment by tmuras** [comment]
Documentation update is always a good idea. I think I should add run-time check to see if my home dir (whatever that may be) is writeable - and then at least advice users.

**Comment by usernamenumber** [comment]
That sounds like a good compromise to me. Maybe add an option to moosh that
allows the user to explicitly say where `.moosh` should be located, and
mention that in the warning message?

**Comment by drfyzziks** [comment]
Time for a grumpy unix sysadmin interjection: This is a unix-like environment we're talking about here. Scripts should respect the value set in $HOME and not make assumptions on where to put things. It's up to the end user to ensure that $HOME is pointing to the right place, which is why the -H argument on sudo exists.

If you must, add a flag to the moosh command line or a configuration file that allows you to specify/override the location of .moosh - but don't make it ignore $HOME.
